if(NOT DEFINED RECIPE_DIR)
	message(FATAL_ERROR "RECIPE_DIR must be passed via -DRECIPE_DIR=...")
endif()

set(_script "${RECIPE_DIR}/UNSUPPORTED.cmake")
if(EXISTS "${_script}")
	unset(SPM_UNSUPPORTED_REASON)
	include("${_script}")
	if(SPM_UNSUPPORTED_REASON)
		message("SPM_UNSUPPORTED:${SPM_UNSUPPORTED_REASON}")
	endif()
endif()
